# Generated by Django 6.0.5 on 2026-09-06 20:40

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('title',
                 models.CharField(max_length=255,
                                  verbose_name='Название документа')),
                ('file',
                 models.FileField(upload_to='regulations/',
                                  verbose_name='Файл документа')),
                ('created_at',
                 models.DateTimeField(auto_now_add=True,
                                      verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('embedding',
                 pgvector.django.vector.VectorField(blank=True,
                                                    dimensions=384,
                                                    null=True)),
                ('is_active',
                 models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at',
                 models.DateTimeField(auto_now_add=True,
                                      verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('embedding',
                 pgvector.django.vector.VectorField(blank=True,
                                                    dimensions=384,
                                                    null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='chunks',
                                   to='support.document')),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('document', 'chunk_index'),
                                            name='unique_document_chunk')
                ],
            },
        ),
    ]
