# Generated by Django 6.0.5 on 2026-08-04 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата заезда')),
                ('end_date', models.DateField(verbose_name='Дата выезда')),
                ('rent_days', models.IntegerField(verbose_name='Количество дней проживания')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.room', verbose_name='Номер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='ReservationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата заезда')),
                ('end_date', models.DateField(verbose_name='Дата выезда')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_drafts', to='rooms.room', verbose_name='Номер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_drafts', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Черновик бронирования',
                'verbose_name_plural': 'Черновики бронирований',
            },
        ),
        migrations.CreateModel(
            name='ReservationDraftService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_services', to='bookings.reservationdraft', verbose_name='Черновик бронирования')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_services', to='bookings.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга черновика бронирования',
                'verbose_name_plural': 'Услуги черновиков бронирования',
                'unique_together': {('reservation_draft', 'service')},
            },
        ),
        migrations.AddField(
            model_name='reservationdraft',
            name='services',
            field=models.ManyToManyField(related_name='reservation_drafts', through='bookings.ReservationDraftService', to='bookings.service'),
        ),
        migrations.AlterUniqueTogether(
            name='reservationdraft',
            unique_together={('user', 'room', 'start_date', 'end_date')},
        ),
    ]
